CREATE TABLE AUDIT_TRAIL
(
    ID                          NUMBER NOT NULL,
    ENTITY_ID                   VARCHAR2(50) NOT NULL,
    ENTITY_NAME                 VARCHAR2(50) NOT NULL,
    ENTITY_PROPERTY             VARCHAR2(50) NOT NULL,
    ENTITY_PROPERTY_OLD_VALUE   VARCHAR2(4000),
    ENTITY_PROPERTY_NEW_VALUE   VARCHAR2(4000),
    OPERATION_TYPE              VARCHAR2(50),
    ACTOR_ID                    NUMBER NOT NULL,
    RELEVANCE_TIME              TIMESTAMP(6) NOT NULL,
    CONSTRAINT PK_AUDIT_TRAIL PRIMARY KEY (ID)
)
